eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 8077
spring:
  data:
     solr:
            host: http://127.0.0.1:8109/solr
            repositories: enabled=true
            zk-host: '127.0.0.1:2181,127.0.0.1:2182,127.0.0.1:2183 '
  application:
    name: service-feign
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  main:
    allow-bean-definition-overriding: true
feign:
  hystrix:
    enabled: true
